/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio8;
import java.util.Scanner;

public class App {
  
    public static void main(String[] args) {
     
        Scanner leitor = new Scanner(System.in);
        
        String texto = "Deseja repetir S - Sim / N - Nao";
        char repetir = 's';
        float dolar,real,dolarDisp;
        
        
        while(repetir == 's' || repetir == 'S') {

            System.out.println("Digite a cotaçao do dolar:");
            dolar = leitor.nextFloat();
            
            System.out.println("Quantos dolares você tem?");
            dolarDisp = leitor.nextFloat();
            
            real = dolarDisp * dolar;
            
            System.out.println("Voce tem R$" + real);
            
            System.out.println(texto);
            repetir = leitor.next().charAt(0);
        }
    }
}
