/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio2;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        
    Scanner leitor = new Scanner(System.in);
    
    char repetir = 's';
    float soma = 0.0f, divisao = 0.0f, multi = 0.0f, sub = 0.0f;
    float n1 = 0.0f;
    float n2 = 0.0f;
    
    while(repetir == 's' || repetir == 'S' ){
        System.out.println("Digite um número: ");
        n1 = leitor.nextFloat();
        System.out.println("Digite outro número");
        n2 = leitor.nextFloat();
        
        soma = n1+n2;
        divisao = n1/n2;
        multi = n1*n2;
        sub = n1-n2;
        
        System.out.println("Soma: " + soma);
        System.out.println("Divisão: " + divisao);
        System.out.println("Multiplicação: " + multi);
        System.out.println("Subtração: " + sub);
        
        System.out.println("Deseja Continuar? S- sim / N - Não");
        repetir = leitor.next().charAt(0);
        
    }
    
    }
}
