/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio11;

import java.util.Scanner;

public class App {
  
    public static void main(String[] args) {
 
        Scanner leitor = new Scanner(System.in);
        
        String texto = "Deseja repetir S - Sim / N - Nao";
        char repetir = 's';
        float precoProd, porcent, valorTotal;
        
        
        while(repetir == 's' || repetir == 'S') {
            System.out.println("Digite o preco do produto a ser vendido: ");
            precoProd = leitor.nextFloat();
            System.out.println("Digita a porcentagem do acrescimo");
            porcent = leitor.nextFloat();
            porcent = porcent/100;
            valorTotal = precoProd + (precoProd*porcent);
            
            System.out.println("O valor total do produto ficou em R$" + valorTotal + "\nValor original era de R$" + precoProd + "\ntaxa de juro em " 
            + porcent + "%");
            
            System.out.println(texto);
            repetir = leitor.next().charAt(0);
        }
}
}
