/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio6;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
         Scanner leitor = new Scanner(System.in);
        
        String texto = "Deseja repetir S - Sim / N - Nao";
        char repetir = 's';
        float n1, n2,n3;
        
        while(repetir == 's' || repetir == 'S') {
        
            System.out.println("Digite um valor para A: ");
            n1 = leitor.nextFloat();
            
            System.out.println("Digite um valor para B: ");
            n2 = leitor.nextFloat();
            
            System.out.println("Numero A: " + n1 + "\nNumero B: " + n2);
            n3 = n1;            
            n1 = n2;
            n2 = n3;
            
            System.out.println("Numero A trocado: " + n1 +"\nNumero B: " + n2);
            
            System.out.println(texto);
            repetir = leitor.next().charAt(0);
                    

        }
            
    }
}
