/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio1;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
       
        Scanner leitor = new Scanner(System.in);
        
        float n1 = 0.0f;
        float n2 = 0.0f;
        float soma = 0.0f;
        char sair = 'n';
        
        
        if(sair == 'n'|| sair == 'N'|| sair == 's'|| sair == 'S' ) {
        while(sair == 'n' || sair == 'N'){
            
            System.out.println("Digite um número: ");
            n1 = leitor.nextFloat();
            System.out.println("Digite outro número");
            n2 = leitor.nextFloat();
            soma = n1 + n2;
            System.out.println("A soma dos dois números é: " + soma);

            System.out.println("Digite S para Sim ou N para Não");
            sair = leitor.next().charAt(0);
        }
       
    }
}
}
        
