/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio4;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        
        Scanner leitor = new Scanner(System.in);
        
        String texto = "Deseja repetir S - Sim / N - Não";
        char repetir = 's';
        float comissao = 0.15f;
        float salario = 1500.0f;
        String nome;
        float vendas;
        float salarioFinal;
        
        while(repetir == 's' || repetir == 'S') {
            System.out.println("Digite o nome do vendedor:");
            nome = leitor.next();
            
            System.out.println("Digite o total de vendas do vendedor");
            vendas = leitor.nextFloat();
           
            salarioFinal = salario + (vendas * comissao);
            
            System.out.println("Nome vendedor: " + nome +
                    "\nSalário Fixo: " + salario +
                    "\nSalário Final: " + salarioFinal);
            
            System.out.println(texto);
            repetir = leitor.next().charAt(0);
            
        }
        
    }
}
