/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio7;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
         Scanner leitor = new Scanner(System.in);
        
        String texto = "Deseja repetir S - Sim / N - Nao";
        char repetir = 's';
        float celsius, fahrenheit;
        
            while(repetir == 's' || repetir == 'S') {

                System.out.println("Digite uma temperatura em Celsius: ");
                celsius = leitor.nextFloat();
                
                fahrenheit =(9*celsius+160)/5;
                
                System.out.println("A temperatura " + celsius + "C" + "\n"
                        + "E de " + fahrenheit + "F");
                
 		System.out.println(texto);
                repetir = leitor.next().charAt(0);
        
    }

    }
}
