/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio9;
import java.util.Scanner;

public class App {
  
    public static void main(String[] args) {
 
Scanner leitor = new Scanner(System.in);
        
        String texto = "Deseja repetir S - Sim / N - Nao";
        char repetir = 's';
        double juros = 0.07f;
        double deposito, rendimento, jurosRendidos;
        int meses;
        
        
        while(repetir == 's' || repetir == 'S') {

            
            System.out.println("Digite o valor a ser depositado:");
            deposito = leitor.nextDouble();
            
            System.out.println("Quantos meses voce vai deixar rendendo:");
            meses = leitor.nextInt();
            
            rendimento = 0.0f;
            for(int i=0; i < meses ; i++) {
                rendimento = deposito *Math.pow((1 + juros), meses);
            }
            
            jurosRendidos = rendimento - deposito;
            
            System.out.println("O valor rendido durante " + meses + " "+ "meses foi de "
            + jurosRendidos + "\n Valor depositado " + deposito + "\nSendo o total de " + rendimento);
 	
            System.out.println(texto);
            repetir = leitor.next().charAt(0);
        
    }

}

}
