/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio12;

import java.util.Scanner;

public class App {
  
    public static void main(String[] args) {
 
        Scanner leitor = new Scanner(System.in);
        
        String texto = "Deseja repetir S - Sim / N - Nao";
        char repetir = 's';
        float imposto = 0.45f;
        float percentual = 0.28f;
        float custoFabrica, valorCarro;
        
        
        while(repetir == 's' || repetir == 'S') {

            System.out.println("Digite o valor do custo da fabrica");
            custoFabrica = leitor.nextFloat();
            valorCarro = custoFabrica + (custoFabrica*imposto);
            valorCarro = valorCarro +(valorCarro*percentual);
            
            System.out.println("O valor do veiculo para o consumido final fica em R$" + valorCarro);
            
            System.out.println(texto);
            repetir = leitor.next().charAt(0);
        }
    }
}