/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio3;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        
        Scanner leitor  = new Scanner(System.in);
        
        float combustivel = 0.0f;
        float distancia = 0.0f;
        float mediaGasta = 0.0f;
        char repetir = 's';
        
        while(repetir == 's' || repetir == 'S'){
            System.out.println("Digite a quantidade de combustivel:");
            combustivel = leitor.nextFloat();
            System.out.println("Digite a distância percorrida: ");
            distancia = leitor.nextFloat();
            
            mediaGasta = distancia/combustivel;
            
            System.out.println("O consumo médio foi de: " + mediaGasta + "Km/L");
            
            System.out.println("Deseja Continuar? S - Sim / N - Não");
            repetir = leitor.next().charAt(0);
        }
        
    }
}
