/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Classes;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        
        //objeto
        //Variavel Não primitiva
        Pessoa p = new Pessoa();
        
        Scanner leitor = new Scanner(System.in);
        
        System.out.println("Digite o peso da pessoa");
        p.setPeso(leitor.nextFloat());
        System.out.println("Digite a altura da pessoa");
        p.setAltura(leitor.nextFloat());

        System.out.println("IMC: " + p.calcularIMC());
         
    }
}
