/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exericio14;

import java.util.Scanner;

public class App {
  
    public static void main(String[] args) {
 
        Scanner leitor = new Scanner(System.in);
        
        String texto = "Deseja repetir S - Sim / N - Nao";
        char repetir = 's';
        int n1, n2;
        
        while(repetir == 's' || repetir == 'S') {

         System.out.println("Digite um numero");
         n1 = leitor.nextInt();
         System.out.println("Digite outro numero");
         n2 = leitor.nextInt();
         
         if(n1> n2){
             System.out.println("O numero " + n1 + " e maior que o " + n2);
         } else {
             System.out.println("O numero " + n2 + " e maior que o " + n1);
         }
            System.out.println(texto);
            repetir = leitor.next().charAt(0);
        }
    }
}
